### ISSUE TITLE
dealing with CORS?

### ISSUE THREAD

**Issue by CatherineBacon** [pilwon/node-google-finance#12]
I'm trying to use node-google-finance in the browser as an ES6 import and seem to be running into CORS errors:

```
Fetch API cannot load https://www.google.com/finance/historical?q=AAPL&startdate=2001-01-01&enddate=2010-12-31&output=csv. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Can anyone advise how to deal with them? I don't know if the request header is exposed so we can change settings?

In case it's any help, here's the live site I'm working on: http://catherinecollinson.com/fcc-chartthestockmarket/

And here's the code where I use googleFinance:
https://github.com/CatherineBacon/fcc-chartthestockmarket/blob/master/src/FinanceData.jsx#L29

Thank you!

**Comment by Tu-Szu-Chi** [comment]
I use the Chrome Extension [Allow-Control-Allow-Origin] to fix
because I only run project in localhost,hope to help you!
