### ISSUE TITLE
Issue with retrieving news for multiple stocks + new news url

### ISSUE THREAD

**Issue by sravia** [pilwon/node-google-finance#18]
1. Latest version does not allow to retrieve news for multiple stocks ( symbols ).

Issue is in "_sanitizeCompanyNews" function.

`(node:78229) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): AssertionError [ERR_ASSERTION]: "options.symbol" must be a non-empty string.
`

`googleFinance.companyNews({
                symbol: [ 'NASDAQ:AAPL', 'NASDAQ:MSFT' ]
            }, function (err, news) {
            });
});`

2. New COMPANY_NEWS_URL is "https://finance.google.com/finance/company_news"

**Comment by pilwon** [comment]
Merged PR #20
